#ifndef CHUNK_FWD_O_TILING_KEY_H
#define CHUNK_FWD_O_TILING_KEY_H

#ifndef TORCH_MODE
#include "ascendc/host_api/tiling/template_argument.h"
#endif

#define CHUNK_FWD_O_PATH_LEGACY 0
#define CHUNK_FWD_O_PATH_A5 1

#ifndef TORCH_MODE
ASCENDC_TPL_ARGS_DECL(
    ChunkFwdO,
    ASCENDC_TPL_UINT_DECL(PATH, 1, ASCENDC_TPL_UI_LIST,
                          CHUNK_FWD_O_PATH_LEGACY, CHUNK_FWD_O_PATH_A5),
    ASCENDC_TPL_BOOL_DECL(STATE_V_FIRST, 0, 1)
);

#define CHUNK_FWD_O_TPL_SEL_ENTRY(PATH_VALUE, STATE_LAYOUT) \
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2), \
                         ASCENDC_TPL_UINT_SEL(PATH, ASCENDC_TPL_UI_LIST, PATH_VALUE), \
                         ASCENDC_TPL_BOOL_SEL(STATE_V_FIRST, STATE_LAYOUT))

ASCENDC_TPL_SEL(
    CHUNK_FWD_O_TPL_SEL_ENTRY(CHUNK_FWD_O_PATH_LEGACY, 0),
    CHUNK_FWD_O_TPL_SEL_ENTRY(CHUNK_FWD_O_PATH_A5, 0),
    CHUNK_FWD_O_TPL_SEL_ENTRY(CHUNK_FWD_O_PATH_A5, 1)
);

#undef CHUNK_FWD_O_TPL_SEL_ENTRY
#endif

#endif // CHUNK_FWD_O_TILING_KEY_H
