/**
 * Copyright (c) 2026 Tianjin University, Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * the BSD 3-Clause License (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 */

/*!
 * \file chunk_delta_h_bwd_preprocess_tiling_key.h
 * \brief Tiling key（ASCENDC_TPL 模板参数）声明 for chunk_delta_h_bwd_preprocess.
 *
 * kernel 侧不使用 TILING_KEY_IS 分支：host 用 GET_TPL_TILING_KEY 算出 key，kernel 的模板实例按 key 直接选中。
 * 因此本文件必须被 op_kernel 与 op_host 两侧同时看到（由 <op>_struct.h 统一转包含）。
 */

#ifndef CHUNK_DELTA_H_BWD_PREPROCESS_TILING_KEY_H
#define CHUNK_DELTA_H_BWD_PREPROCESS_TILING_KEY_H

#ifndef TORCH_MODE
#include "ascendc/host_api/tiling/template_argument.h"
#endif

namespace CP {

// 模板参数（kernel 侧不用 TILING_KEY_IS 分支，由 TPL tilingKey 直接选中模板实例）：
//   D_T_Q     : q/k/w/d_o/dv 的 dtype（BF16 / FP16）
//   D_T_G     : 标量 gate `g` 的 dtype（BF16 / FP16 / FP32）；无门控时取与 D_T_Q 相同，避免多余实例
//   GATE_MODE : 0 无门控 / 1 标量 gate `g` / 2 逐 K gate `gk`
//
// 注意：模板参数的取值必须是宏（ASCENDC_TPL_*_DECL 由工具链按文本解析），不能用 constexpr 变量。
#define CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_NONE 0
#define CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_SCALAR 1
#define CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_PER_K 2

#define CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16 10
#define CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16 20
#define CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP32 30

#ifndef TORCH_MODE
ASCENDC_TPL_ARGS_DECL(
    ChunkDeltaHBwdPreprocess,
    ASCENDC_TPL_DTYPE_DECL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16),
    ASCENDC_TPL_DTYPE_DECL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16,
                           CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP32),
    ASCENDC_TPL_UINT_DECL(GATE_MODE, 2, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_NONE,
                          CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_SCALAR,
                          CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_PER_K));

ASCENDC_TPL_SEL(
    // 无门控：g/gk 都不传，D_T_G 与 D_T_Q 相同
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(GATE_MODE, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_NONE)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(GATE_MODE, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_NONE)),
    // 标量 gate：g 与 q 同 dtype 或 FP32
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(GATE_MODE, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_SCALAR)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(GATE_MODE, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_SCALAR)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(GATE_MODE, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_SCALAR)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP32),
        ASCENDC_TPL_UINT_SEL(GATE_MODE, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_SCALAR)),
    // 逐 K gate：gk 必须与 q 同 dtype
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_BF16),
        ASCENDC_TPL_UINT_SEL(GATE_MODE, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_PER_K)),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_DTYPE_SEL(D_T_Q, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16),
        ASCENDC_TPL_DTYPE_SEL(D_T_G, CHUNK_DELTA_H_BWD_PREPROCESS_TPL_FP16),
        ASCENDC_TPL_UINT_SEL(GATE_MODE, ASCENDC_TPL_UI_LIST, CHUNK_DELTA_H_BWD_PREPROCESS_GATE_MODE_PER_K)));
#endif

} // namespace CP

#endif // CHUNK_DELTA_H_BWD_PREPROCESS_TILING_KEY_H
