/**
 * Copyright (c) 2026 Tianjin University, Ltd.
 * Licensed under the BSD 3-Clause License.
 */
#ifndef CHUNK_KDA_BWD_RECOMPUTE_TILING_KEY_H
#define CHUNK_KDA_BWD_RECOMPUTE_TILING_KEY_H

#define CHUNK_KDA_BWD_RECOMPUTE_BETA_BF16 1U
#define CHUNK_KDA_BWD_RECOMPUTE_BETA_FP32 2U
#define CHUNK_KDA_BWD_RECOMPUTE_GATE_BF16 4U
#define CHUNK_KDA_BWD_RECOMPUTE_GATE_FP32 8U

#endif // CHUNK_KDA_BWD_RECOMPUTE_TILING_KEY_H
