/**
 * Copyright (c) 2026 Tianjin University, Ltd.
 * Licensed under the BSD 3-Clause License.
 */
#ifndef CHUNK_KDA_BWD_RECOMPUTE_TILING_KEY_H
#define CHUNK_KDA_BWD_RECOMPUTE_TILING_KEY_H

#ifndef TORCH_MODE
#include "ascendc/host_api/tiling/template_argument.h"
#endif

namespace KDA {

#define CHUNK_KDA_BWD_RECOMPUTE_TPL_BF16 10
#define CHUNK_KDA_BWD_RECOMPUTE_TPL_FP32 30

#ifndef TORCH_MODE
ASCENDC_TPL_ARGS_DECL(ChunkKdaBwdRecompute,
    ASCENDC_TPL_DTYPE_DECL(D_T_G, CHUNK_KDA_BWD_RECOMPUTE_TPL_BF16, CHUNK_KDA_BWD_RECOMPUTE_TPL_FP32),
    ASCENDC_TPL_DTYPE_DECL(D_T_BETA, CHUNK_KDA_BWD_RECOMPUTE_TPL_BF16, CHUNK_KDA_BWD_RECOMPUTE_TPL_FP32),
    ASCENDC_TPL_UINT_DECL(K_DIM, ASCENDC_TPL_1_BW, ASCENDC_TPL_UI_LIST, 128),
);

#define CHUNK_KDA_BWD_RECOMPUTE_TPL_SEL_ONE(G_TYPE, BETA_TYPE) \
    ASCENDC_TPL_ARGS_SEL( \
        ASCENDC_TPL_DTYPE_SEL(D_T_G, G_TYPE), \
        ASCENDC_TPL_DTYPE_SEL(D_T_BETA, BETA_TYPE), \
        ASCENDC_TPL_UINT_SEL(K_DIM, ASCENDC_TPL_UI_LIST, 128), \
    )

#define CHUNK_KDA_BWD_RECOMPUTE_TPL_SEL_BETA(G_TYPE) \
    CHUNK_KDA_BWD_RECOMPUTE_TPL_SEL_ONE(G_TYPE, CHUNK_KDA_BWD_RECOMPUTE_TPL_BF16), \
    CHUNK_KDA_BWD_RECOMPUTE_TPL_SEL_ONE(G_TYPE, CHUNK_KDA_BWD_RECOMPUTE_TPL_FP32)

ASCENDC_TPL_SEL(
    CHUNK_KDA_BWD_RECOMPUTE_TPL_SEL_BETA(CHUNK_KDA_BWD_RECOMPUTE_TPL_BF16),
    CHUNK_KDA_BWD_RECOMPUTE_TPL_SEL_BETA(CHUNK_KDA_BWD_RECOMPUTE_TPL_FP32),
);

#undef CHUNK_KDA_BWD_RECOMPUTE_TPL_SEL_BETA
#undef CHUNK_KDA_BWD_RECOMPUTE_TPL_SEL_ONE
#endif

} // namespace KDA

#endif // CHUNK_KDA_BWD_RECOMPUTE_TILING_KEY_H
