#!/usr/bin/env python3
"""Build libfla_npu_stable.so against the torch Stable ABI.

The Stable-ABI headers are the vendored copy in `include/torch_stable_abi`
(pinned to torch 2.9 -- see its README for why) rather than the build torch's:
the build has to work on a torch that predates them (2.7.1 ships only
`library.h`) and must not inherit a newer revision's symbol references.  The
produced shared library must not reference any C++ ATen/c10 symbol (the ELF
audit in tools/stable_abi_audit.py asserts that).

Link line: the artifact is a *plain* shared library (no Python module), so it is
loaded later via torch.ops.load_library().  We link libtorch_cpu.so only so the
aoti_torch_* shims resolve; the loader reuses the already-loaded library through
its unversioned SONAME, which is what makes the artifact version-agnostic.

Usage:
  python csrc/build_stable.py [--out PATH] [--compiler CXX]
                                     [--no-debug-probe] [--verbose]
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]          # torch_custom/fla_npu
CSRC = ROOT / "csrc" / "src"
CSRC_INCLUDE = ROOT / "csrc" / "include"
HASH_MODULE = ROOT / "fla_npu" / "ops" / "ascendc" / "_stable_hash.py"

# One TU by construction: the stable headers may not be included twice
# (non-inline definitions in tensor_inl.h -> duplicate symbols), so the adapter
# sources are included into stable_ops.cpp rather than compiled side by side.
# The gates read this tuple so they check what is actually built.
TRANSLATION_UNITS = (CSRC / "stable_ops.cpp",
                     CSRC / "runtime.cpp")


def source_hash() -> str:
    """md5 of the adapters this build compiles in.

    The stamp is per-file sorted and covers both the sources and their shared
    headers, because an adapter and `stable/exec.h` have to be in step:
    a .so left over from an earlier build otherwise fails deep inside the
    dispatcher, or -- when only a stack index moved -- silently launches on a
    stale stream.

    Each file is prefixed with its name and its newlines are normalised: git
    checks files out with CRLF on Windows and LF everywhere else, and a stamp
    that changed with the checkout would reject a perfectly good library.
    """

    digest = hashlib.md5()
    sources = sorted(CSRC.glob("*.cpp")) + sorted(
        CSRC_INCLUDE.rglob("*.h"))
    for path in sources:
        digest.update(path.name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(_normalised(path.read_bytes()))
        digest.update(b"\0")
    return digest.hexdigest()


def _normalised(payload: bytes) -> bytes:
    return payload.replace(b"\r\n", b"\n")


def write_hash_module(value: str) -> None:
    """Record the stamp the Python glue checks the loaded library against."""

    HASH_MODULE.write_text(
        '"""Generated by csrc/build_stable.py -- do not edit.\n\n'
        "The adapters the bundled libfla_npu_stable.so was compiled from; see\n"
        "``_stable._check_build_stamp``.\n"
        '"""\n\n'
        f'SOURCE_HASH = "{value}"\n',
        encoding="utf-8")


def torch_lib_dir() -> str:
    """Path to the torch shared libraries the launcher links against.

    Only the *library* path is needed.  Keeping the link is deliberate: the
    aoti_torch_* calls stay ordinary dynamically-resolved calls, so the change
    that moved the headers into the tree does not touch the call path at all
    (no dlsym, no extra indirection).
    """

    try:
        import torch
    except ImportError as exc:
        # Without torch there is nothing to link against, and the failure would
        # otherwise arrive as a traceback from inside an import.
        raise SystemExit(
            "fla_npu: torch is not importable, so libfla_npu_stable.so cannot "
            "be linked against libtorch_cpu.so.  Install torch >= 2.7.1 in the "
            f"build environment first ({exc}).") from exc

    return str(Path(torch.__file__).parent / "lib")


def torch_include_dirs() -> list[str]:
    """Include paths for the adapters: the vendored headers, then torch's own.

    The vendored copy comes first so it wins where both exist, which is what
    pins the interface to the revision the runtime floor supports.  The build
    torch's paths are a fallback and are never required -- torch 2.7.1 does not
    ship `tensor.h` or `stableivalue_conversions.h` at all.
    """

    dirs = [str(CSRC_INCLUDE / "torch_stable_abi")]
    try:
        from torch.utils import cpp_extension
    except ImportError:
        # The vendored closure is complete, so a build without the fallback is
        # still a supported build; only the torch dirs go missing.  Report it
        # instead of letting a half-configured environment pass unnoticed.
        print("[fla-npu stable] torch.utils.cpp_extension is unavailable; "
              "building with the vendored headers alone", file=sys.stderr)
        return dirs
    dirs.extend(cpp_extension.include_paths())
    return dirs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(ROOT / "libfla_npu_stable.so"))
    parser.add_argument("--compiler", default=os.environ.get("CXX", "g++"))
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--no-debug-probe", action="store_true",
                        help="drop the _stream_probe op (smaller symbol surface)")
    args = parser.parse_args()

    torch_lib = torch_lib_dir()
    stamp = source_hash()
    cmd = [
        args.compiler,
        "-std=c++17",
        "-O2",
        "-fPIC",
        "-shared",
        "-fvisibility=hidden",
        *(["-DFLA_STABLE_NO_DEBUG_PROBE"] if args.no_debug_probe else []),
        f'-DFLA_STABLE_SOURCE_HASH="{stamp}"',
        "-I", str(CSRC_INCLUDE),
        *[f"-I{path}" for path in torch_include_dirs()],
        *[str(path) for path in TRANSLATION_UNITS],
        # The runtime (dlopen + symbol cache) ships with the launcher.
        "-L", torch_lib,
        "-Wl,--no-as-needed", "-ltorch_cpu", "-lc10", "-ltorch",
        "-ldl",
        "-o", args.out,
    ]
    print(" ".join(cmd))
    if shutil.which(args.compiler) is None:
        raise SystemExit(f"compiler {args.compiler!r} not found")
    subprocess.run(cmd, check=True)
    write_hash_module(stamp)
    print(f"built {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
