/**
 * Copyright (c) 2026 Tianjin University, Ltd.
 * Licensed under the BSD 3-Clause License.
 */
#ifndef CHUNK_GDN_BWD_INTRA_TILING_KEY_H
#define CHUNK_GDN_BWD_INTRA_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define CHUNK_GDN_BWD_INTRA_FIXED 0
#define CHUNK_GDN_BWD_INTRA_VARLEN 1
#define CHUNK_GDN_BWD_INTRA_MAIN_BF16 0
#define CHUNK_GDN_BWD_INTRA_MAIN_FP16 1
#define CHUNK_GDN_BWD_INTRA_GATE_BF16 0
#define CHUNK_GDN_BWD_INTRA_GATE_FP32 1
#define CHUNK_GDN_BWD_INTRA_BETA_BF16 0
#define CHUNK_GDN_BWD_INTRA_BETA_FP32 1

ASCENDC_TPL_ARGS_DECL(
    ChunkGdnBwdIntra,
    ASCENDC_TPL_UINT_DECL(STRATEGY_KEY, 1, ASCENDC_TPL_UI_LIST,
                          CHUNK_GDN_BWD_INTRA_FIXED, CHUNK_GDN_BWD_INTRA_VARLEN),
    ASCENDC_TPL_UINT_DECL(MAIN_KEY, 1, ASCENDC_TPL_UI_LIST,
                          CHUNK_GDN_BWD_INTRA_MAIN_BF16, CHUNK_GDN_BWD_INTRA_MAIN_FP16),
    ASCENDC_TPL_UINT_DECL(GATE_KEY, 1, ASCENDC_TPL_UI_LIST,
                          CHUNK_GDN_BWD_INTRA_GATE_BF16, CHUNK_GDN_BWD_INTRA_GATE_FP32),
    ASCENDC_TPL_UINT_DECL(BETA_KEY, 1, ASCENDC_TPL_UI_LIST,
                          CHUNK_GDN_BWD_INTRA_BETA_BF16, CHUNK_GDN_BWD_INTRA_BETA_FP32));

#define CHUNK_GDN_BWD_INTRA_TPL_ENTRY(STRATEGY, MAIN, GATE, BETA)                         \
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(STRATEGY_KEY, ASCENDC_TPL_UI_LIST, STRATEGY), \
                         ASCENDC_TPL_UINT_SEL(MAIN_KEY, ASCENDC_TPL_UI_LIST, MAIN),          \
                         ASCENDC_TPL_UINT_SEL(GATE_KEY, ASCENDC_TPL_UI_LIST, GATE),          \
                         ASCENDC_TPL_UINT_SEL(BETA_KEY, ASCENDC_TPL_UI_LIST, BETA))

ASCENDC_TPL_SEL(
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(0, 0, 0, 0),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(0, 0, 0, 1),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(0, 0, 1, 0),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(0, 0, 1, 1),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(0, 1, 0, 0),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(0, 1, 0, 1),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(0, 1, 1, 0),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(0, 1, 1, 1),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(1, 0, 0, 0),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(1, 0, 0, 1),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(1, 0, 1, 0),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(1, 0, 1, 1),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(1, 1, 0, 0),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(1, 1, 0, 1),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(1, 1, 1, 0),
    CHUNK_GDN_BWD_INTRA_TPL_ENTRY(1, 1, 1, 1));

#undef CHUNK_GDN_BWD_INTRA_TPL_ENTRY

#endif // CHUNK_GDN_BWD_INTRA_TILING_KEY_H
